- stage: Build
  displayName: 'Prepare Application for Deployment'
  jobs:
  - job: BuildApp
    steps:
    - script: |
        echo Installing TypeScript...
        npm install -g typescript
        npm install --save-dev typescript

        echo Compiling TypeScript...
        npx tsc --version
        npx tsc
      displayName: 'Build TypeScript App'
