trigger: 
  branches:
    include:
      - main  # Runs when you push to the main branch

pool:
  name: Default  # Uses your self-hosted agent

stages:
- stage: Checkout
  displayName: 'Checkout Repository'
  jobs:
  - job: Checkout
    steps:
    - checkout: self  # Clones the GitHub repository

- stage: Install_Dependencies
  displayName: 'Install Dependencies'
  jobs:
  - job: Install
    steps:
    - script: |
        npm install
        npx playwright install  # Installs Playwright browsers
      displayName: 'Install npm packages'

- stage: Build
  displayName: 'Prepare Application for Deployment'
  jobs:
  - job: BuildApp
    steps:
    - script: |
        npm run build
      displayName: 'Build App'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
      displayName: 'Archive Application Files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifactName: 'drop'
      displayName: 'Publish Artifact'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  jobs:
  - job: DeployApp
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '<Your Azure Service Connection>'
        appName: 'your-app-name'  # Replace with your actual Azure App Service name
        package: '$(Build.ArtifactStagingDirectory)/drop/app.zip'
        runtimeStack: 'NODE|18-lts'
      displayName: 'Deploy to Azure Web App'
