trigger: 
  branches:
    include:
      - main  # Runs the pipeline when code is pushed to 'main' branch

pool:
  name: Default  # Uses your self-hosted agent instead of Azure-hosted agents

stages:
- stage: Checkout
  displayName: 'Checkout Repository'
  jobs:
  - job: Checkout
    steps:
    - checkout: self  # Clones the GitHub repository

- stage: Install_Dependencies
  displayName: 'Install Dependencies'
  jobs:
  - job: Install
    steps:
    - script: |
        npm install
        npx playwright install  # Installs Playwright browsers
      displayName: 'Install npm packages'

- stage: Start_Application
  displayName: 'Start Application'
  jobs:
  - job: StartApp
    steps:
    - script: |
        start /b npm start  # Starts the app in the background
        timeout /t 10  # Wait for 10 seconds (adjust if needed)
      displayName: 'Start Express Server'

- stage: Run_Tests
  displayName: 'Run Playwright Tests'
  dependsOn: Start_Application  # Ensures tests run after the app starts
  jobs:
  - job: Test
    steps:
    - script: |
        npx playwright test tests/hello-world.spec.ts
      displayName: 'Run Playwright Tests'
