pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'git@github.com:karolinasobczak1988/newRepo.git'  // Replace with your actual repo URL
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'nohup node dist/index.js &'
            }
        }
    }
}
