pipeline { 
    agent any
    environment {
        GIT_CREDENTIALS = credentials('ssh-ed25519')
    }
    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'git@github.com:karolinasobczak1988/newRepo.git',
                    credentialsId: 'ssh-ed25519'
                )
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
      stage('Run Playwright Tests') {
    steps {
        script {
            // List files in the workspace to verify test file exists
          //  sh 'dir /s /b'

            // Run the Playwright test with the specified test file
            sh 'npx playwright test'

           // sh "npx playwright test src/tests/hello-world.spec.ts"
        }
    }
}